### ISSUE TITLE
Add an OSS license

### ISSUE THREAD

**Issue by karan** [nigelbabu/mozalien#2]
Please add an OSS license for the usage and distribution of the code. I'd like to hack on it, but am not sure what my limitations are.

**Comment by nigelbabu** [comment]
Fixed in https://github.com/nigelbabu/mozalien/commit/2d9b37ce81ab04a9bf9042dae3029f1570be2b9c. Sorry about the delay. I missed the bug report! This project is now licensed with an MIT License.
